# Generated by Django 5.1.2 on 2025-02-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instrucciones', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cocktails/')),
                ('vaso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('encrypted_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIngrediente', models.CharField(max_length=100)),
                ('cantidadIngrediente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktailsPersonalapp.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktailsPersonalapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoCocktailDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_cocktaildb', to='cocktailsPersonalapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to='cocktailsPersonalapp.user'),
        ),
    ]
