# Generated by Django 5.1.2 on 2025-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailsPersonalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
