# Generated by Django 5.1.2 on 2025-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailsPersonalapp', '0002_alter_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
