# Generated by Django 5.1.2 on 2025-02-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailsPersonalapp', '0002_alter_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to='cocktailsPersonalapp.user'),
            preserve_default=False,
        ),
    ]
